#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

use strict;
use warnings;
use Complete::Util qw(complete_array_elem);
use Getopt::Long::Complete qw(GetOptionsWithCompletion);

my %opts = (cols => 1, bg=>0);
my $res = GetOptionsWithCompletion(
    sub {
        my %args = @_;
        my $word = $args{word};
        my $type = $args{type};

        if ($type eq 'arg') {
            my $argpos = $args{argpos};
            return complete_array_elem(
                array=>["arg$argpos-a", "arg$argpos-b"], word=>$word);
        } elsif ($type eq 'optval') {
            my $opt = $args{opt};
            if ($opt eq '--int-comp-array') {
                return complete_array_elem(array=>[1..10], word=>$word);
            } elsif ($opt eq '--str-comp-sub') {
                return complete_array_elem(array=>[map {"$word$_"} "a".."z"],
                                           word=>$word);
            } elsif ($opt =~ /\A(--planet|-P|--opt-planet|-p)\z/) {
                return {
                    words => complete_array_elem(
                        array=>[
                            "mercury",
                            "venus",
                            "mars",
                        ],
                        word=>$word,
                    ),
                    path_sep => '::',
                };
            }
        }

        undef;
    },
    'flag1|1' => sub{},
    'flag2|f' => sub{},
    'bool|b!' => sub{},
    'int=i' => sub{},

    # to demonstrate completing optval
    'planet|P=s' => sub{},
    'opt-planet|p:s' => sub{},

    'float|F=f' => sub{},
    'str|text|S=s' => sub{},
    'array=s@' => sub{},
    'int-comp-array=i' => sub{},
    'str-comp-sub=s' => sub{},

    'version|v' => sub{
        no warnings;
        print "demo-getopt-long-complete version $main::VERSION\n";
        exit 0;
    },
    'help|h|?' => sub {
        print <<_;
Usage:
  $0 --help (or -h, -?)
  $0 [opts]

Options:
  --array=s@
  --(no)bool, -b
  --flag1, -1
  --flag2, -f
  --float=f, -F
  --fruit=s
  --int-comp-array=i
  --int=i
  --opt-planet:s, -p
  --planet=s, -P
  --str-comp-sub=s
  --str=s, --text, -S
_
        exit 0;
    },
);

#print $res ? "Getopt failed\n" : "Getopt succeeded\n";

# ABSTRACT: Script to demonstrate Getopt::Long::Complete
# PODNAME:

=head1 SYNOPSIS

Activate completion using (can be put in your bash startup file):

 % complete -C demo-getopt-long-complete demo-getopt-long-complete

Test completion:

 % demo-getopt-long-complete <tab>
 % demo-getopt-long-complete -<tab>
 % demo-getopt-long-complete --int 1 -<tab>
 # and so on

=head2
